In [1]:
import sympy as sym
import numpy as np
import pandas as pd
from IPython.display import display, Math
sym.init_printing()

In [2]:
A = np.array([[1,2], [3,4]])
print(A)
display(Math(sym.latex(sym.simplify(A))))

[[1 2]
 [3 4]]


<IPython.core.display.Math object>

In [3]:
# Declare a variable and assign a matrix of zeros 4 rows 5 cols
mat = np.zeros([4,5])
mat

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
# Manually change some of the entries in the matrix
mat[0,3]  = 3
mat[3, 4] = 7
mat

array([[0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 7.]])

In [5]:
mat1 = np.zeros([3,3])
mat1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
from sympy.abc import x,y
exper = (4+x)*(2-y)
for i in range(0, 3):
    for j in range(0, 3):
        mat1[i,j] = exper.subs({x:i, y:j})
        
        
display(Math(sym.latex(sym.simplify(mat1))))

<IPython.core.display.Math object>

## Date: 19/06/2021

#### Exercise 


##### Creating a multiplication Table

In [8]:
table_mat = np.zeros([10,10])
table_mat


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
table_mat[-9]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
for i in range(1,10):
    for j in range(1,10):
        table_mat[i,j] = int(i*j)

In [11]:
display(Math(sym.latex(sym.simplify(table_mat))))

<IPython.core.display.Math object>

In [12]:
num = range(1,11)

table_mat = np.zeros((len(num), len(num) ), dtype = int)
table_mat
for i in num:
    for j in num:
        table_mat[i-1, j-1] = (i*j)

In [13]:
display(Math(sym.latex(sym.simplify(table_mat))))

<IPython.core.display.Math object>

In [14]:
table_mat[6-1][6-1]

36